/****************************************************/
/*	Author	:Ayman Saleh							*/
/*	Date	:12 SEP 2022 							*/
/*	Version	:V01		 							*/
/****************************************************/

/*	Header File Guard
	if file is not defined 
 */
#ifndef EXTI_CONFIG_H_
#define EXTI_CONFIG_H_

/*	Options :
		ENABLE
		DISABLE
*/
#define EXTI_LINE0	ENABLE
#define EXTI_LINE1	DISABLE
#define EXTI_LINE2	DISABLE
#define EXTI_LINE3	DISABLE
#define EXTI_LINE4	DISABLE
#define EXTI_LINE5	DISABLE
#define EXTI_LINE6	DISABLE
#define EXTI_LINE7	DISABLE
#define EXTI_LINE8	DISABLE
#define EXTI_LINE9	DISABLE
#define EXTI_LINE10	DISABLE
#define EXTI_LINE11	DISABLE
#define EXTI_LINE12	DISABLE
#define EXTI_LINE13	DISABLE
#define EXTI_LINE14	DISABLE
#define EXTI_LINE15	DISABLE

/*	Sensitivity Mode
	Options:	
		RISING
		FALLING
		ON_CHANGE
*/
#define EXTI_SENSE_MODE_LINE0	FALLING
#define EXTI_SENSE_MODE_LINE1	ON_CHANGE
#define EXTI_SENSE_MODE_LINE2	ON_CHANGE
#define EXTI_SENSE_MODE_LINE3	ON_CHANGE
#define EXTI_SENSE_MODE_LINE4	ON_CHANGE
#define EXTI_SENSE_MODE_LINE5	ON_CHANGE
#define EXTI_SENSE_MODE_LINE6	ON_CHANGE
#define EXTI_SENSE_MODE_LINE7	ON_CHANGE
#define EXTI_SENSE_MODE_LINE8	ON_CHANGE
#define EXTI_SENSE_MODE_LINE9	ON_CHANGE
#define EXTI_SENSE_MODE_LINE10	ON_CHANGE
#define EXTI_SENSE_MODE_LINE11	ON_CHANGE
#define EXTI_SENSE_MODE_LINE12	ON_CHANGE
#define EXTI_SENSE_MODE_LINE13	ON_CHANGE
#define EXTI_SENSE_MODE_LINE14	ON_CHANGE
#define EXTI_SENSE_MODE_LINE15	ON_CHANGE



/*	Call Back Options
	Options:
		NULL
		[Any Application Function]
*/
#define EXTI_CALL_BACK_LINE0	NULL
#define EXTI_CALL_BACK_LINE1    NULL
#define EXTI_CALL_BACK_LINE2    NULL
#define EXTI_CALL_BACK_LINE3    NULL
#define EXTI_CALL_BACK_LINE4    NULL
#define EXTI_CALL_BACK_LINE5    NULL
#define EXTI_CALL_BACK_LINE6    NULL
#define EXTI_CALL_BACK_LINE7    NULL
#define EXTI_CALL_BACK_LINE8    NULL
#define EXTI_CALL_BACK_LINE9    NULL
#define EXTI_CALL_BACK_LINE10   NULL
#define EXTI_CALL_BACK_LINE11   NULL
#define EXTI_CALL_BACK_LINE12   NULL
#define EXTI_CALL_BACK_LINE13   NULL
#define EXTI_CALL_BACK_LINE14   NULL
#define EXTI_CALL_BACK_LINE15   NULL

#endif
